import type { Metadata } from "next";
import "./globals.css";
import Sidebar from "./layout/sidebar/Sidebar";
import Main from "./layout/main/Main";
import MainFooter from "./layout/footer/MainFooter";

export const metadata: Metadata = {
  title: "Resumizeme",
  description: "Generated by create next app",
  icons: {
    icon: "./logo.png",
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <div className="flex min-h-screen">
          <div className="w-[240px] h-[1051px] border-r border-gray-300 ">
            <Sidebar />
          </div>

          <div className="flex-1">
            <div className="container mx-auto w-[960px] h-[1066px] p-[32px] gap-[32px]">
              {children}
              <Main />
            </div>

            <div className="container mx-auto w-[960px] flex flex-col items-center">
              <MainFooter />
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}